### ISSUE TITLE
cannot reshape array of size 2940000 into shape (980,20,50,1)

### ISSUE THREAD

**Issue by minhdl93** [WayneDW/sentiment_analysis#6]
Hi,

When I run model_cnn.py, the program stop with this error. Could you suggest me some solution?

Thank you

Traceback (most recent call last):
  File "C:/Users/minhdl/PycharmProjects/stocks/model_cnn.py", line 103, in <module>
    main()
  File "C:/Users/minhdl/PycharmProjects/stocks/model_cnn.py", line 99, in main
    model_selection(clusters)
  File "C:/Users/minhdl/PycharmProjects/stocks/model_cnn.py", line 89, in model_selection
    X_train, y_train, X_valid, y_valid, X_test, y_test = get_Feature_Label(clusters=clusters)
  File "C:/Users/minhdl/PycharmProjects/stocks/model_cnn.py", line 43, in get_Feature_Label
    X = X.reshape(X.shape[0], 20, 50, 1).astype('float32')
ValueError: cannot reshape array of size 2940000 into shape (980,20,50,1)

**Comment by WayneDW** [comment]
Hi, @DangLienMinh , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it.
